name: "[Release] Scafflater"

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  release-to-npmjs:
    name: "Releasing NPM Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.release.tag_name}}

      - name: Configure CI Git User
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Setup node 15.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x

      - name: Setup npm
        run: npm install -g npm@7.19.0

      - name: Npm Version
        run: npm --version

      - name: NPM Authentication
        run: echo //registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get version from label
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Version to publish
        run: echo ${{ steps.get_version.outputs.version-without-v }}

      - name: Bumping package versions
        run: npm version ${{ steps.get_version.outputs.version-without-v }} --workspaces
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Shrinkwrap
        run: npm run shrinkwrap --workspaces

      - name: Generate Types
        run: npm run types

      - name: Publishing packages
        run: npm publish --workspaces
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
