name: "[Release] Scafflater"

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  release-scafflater:
    name: "Release Scafflater"
    runs-on: ubuntu-latest
    env:
      working-diretory: ./packages/scafflater

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{github.event.release.tag_name}}

      - name: Configure CI Git User
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Setup node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup npm
        run: npm install -g npm@7.19.0

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3.3.2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ubuntu-latest-node-

      - name: Get version from label
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Bumping package versions
        run: |
          npm version ${{ steps.get_version.outputs.version-without-v }} --no-git-tag-version && \
          git add . && \
          git commit -m"Bump Scafflater: ${{ steps.get_version.outputs.version }}"
        working-directory: ${{env.working-diretory}}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-diretory}}

      - name: Generate Types
        run: npm run types
        working-directory: ${{env.working-diretory}}

      - name: NPM Authentication
        run: echo //registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}} > .npmrc
        working-directory: ${{env.working-diretory}}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing packages
        run: npm publish --access=public
        working-directory: ${{env.working-diretory}}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  release-scafflater-cli:
    needs: release-scafflater

    name: "Release Scafflater Cli"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{github.event.release.tag_name}}

      - name: Configure CI Git User
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Setup node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup npm
        run: npm install -g npm@7.19.0

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3.3.2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ubuntu-latest-node-

      - name: Get version from label
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Bumping package versions
        run: |
          npm version ${{ steps.get_version.outputs.version-without-v }} --no-git-tag-version && \
          git add . && \
          git commit -m"Bump Scafflater ${{ steps.get_version.outputs.version }}"
        working-directory: ./packages/scafflater-cli
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/scafflater-cli

      - name: Install scafflater
        run: npm install @scafflater/scafflater@=${{ steps.get_version.outputs.version }}
        working-directory: ./packages/scafflater-cli

      - name: NPM Authentication
        run: echo //registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}} > .npmrc
        working-directory: ./packages/scafflater-cli
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing packages
        run: npm publish --access=public
        working-directory: ./packages/scafflater-cli
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
